using System.Globalization;
using System.Windows.Markup;

namespace SocRcManager.Localization;

/// <summary>
/// Textos de la aplicacion en español e ingles (constitucion, seccion 7). Ningun texto va en el
/// XAML ni en el codigo: todo pasa por aqui.
/// </summary>
public static class Loc
{
    private static readonly Dictionary<string, string> English = new()
    {
        ["AppTitle"] = "sOC Remote Connections Manager",
        ["AboutTitle"] = "About",
        ["AboutTooltip"] = "About",
        ["AboutDescription"] = "Your RDP and SSH connections in one place: a tree of servers, and each session in a tab.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contact",
        ["WriteAuthor"] = "Write to the author",
        ["ContactHint"] = "Suggestions, bugs and ideas: all of it gets read.",
        ["LanguageTitle"] = "Language",
        ["LanguageHint"] = "The language applies right away.",
        ["Privacy"] = "Privacy",
        ["PrivacyText"] = "Connections are stored on this PC only, in your user profile; passwords are encrypted with Windows (DPAPI) for your account. Sessions go straight from this PC to your servers. Nothing goes anywhere else. No ads, no trackers, no analytics.",
        ["License"] = "License",
        ["LicenseText"] = "Free software under the MIT licence. SSH.NET (MIT) and the rest of third-party components are listed in THIRD-PARTY-NOTICES.md. The Remote Desktop control is the one built into Windows.",
        ["LicenseLine"] = "MIT License · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Legal notice",
        ["LegalText1"] = "This software is provided \"as is\", without warranty of any kind, express or implied.",
        ["LegalText2"] = "In no event shall the authors be liable for any claim, damages or other liability arising from the use of this software.",
        ["WarningText"] = "⚠️ Use at your own risk",
        ["Close"] = "Close",
        ["LanguageTooltip"] = "Español / English",

        ["SearchHint"] = "Search…",
        ["NewFolderTooltip"] = "New folder",
        ["NewConnectionTooltip"] = "New connection",
        ["EditTooltip"] = "Edit",
        ["DuplicateTooltip"] = "Duplicate",
        ["DeleteTooltip"] = "Delete",
        ["ConnectTooltip"] = "Connect",
        ["DisconnectTooltip"] = "Disconnect this tab",
        ["FullScreenTooltip"] = "Full screen (F11; Ctrl+Esc to come back)",
        ["ExitFullScreenTooltip"] = "Leave full screen (Ctrl+Esc)",
        ["OpenFileTooltip"] = "Open the connections file folder",
        ["ImportTooltip"] = "Import from Remote Desktop Manager (.rdm)",
        ["Imported"] = "Imported {0} connections ({1} already existed, {2} of unsupported types skipped). Passwords are not imported: they are asked for when connecting.",
        ["ImportFailed"] = "Could not import: {0}",
        ["SettingsTooltip"] = "Settings: where connections are stored",
        ["ImportTitle"] = "Import from Remote Desktop Manager",
        ["ImportIntro"] = "Reads an exported .rdm file and keeps its folders. Passwords are not imported (RDM encrypts them with its own key).",
        ["SettingsTitle"] = "Settings",
        ["StorageTitle"] = "Where connections are stored",
        ["StorageIntro"] = "On this PC only, or in your Google Drive or OneDrive so they follow you to other PCs. In the cloud the file is encrypted with a passphrase only you know.",
        ["StorageLocal"] = "This PC",
        ["StorageLocalHint"] = "Connections stay in the user profile of this PC; nothing leaves it.",
        ["StorageGoogleHint"] = "Sign in with Google: the file goes to the private folder of this app in your Drive (no access to your other files).",
        ["StorageOneDriveHint"] = "Sign in with Microsoft: the file goes to the app folder in your OneDrive (no access to your other files).",
        ["StorageAccount"] = "Signed in as {0} · last sync: {1}",
        ["StorageNowLocal"] = "Connections now stay on this PC. What was uploaded remains in your account until you delete it there.",
        ["Never"] = "never",
        ["PassphraseTitle"] = "Encryption passphrase",
        ["PassphraseIntro"] = "The cloud file is encrypted with it (AES-256). It never leaves this PC and is not stored in your account: use the same one on every PC. If you forget it, the cloud copy cannot be read.",
        ["PassphraseSaveTooltip"] = "Save the passphrase and sync",
        ["SyncNowTooltip"] = "Sync now",
        ["PassphraseSet"] = "Passphrase saved on this PC.",
        ["PassphraseMissing"] = "No passphrase yet: nothing is uploaded until you set one.",
        ["PassphraseTooShort"] = "Use at least 8 characters.",
        ["SigningInBrowser"] = "Finishing sign-in in the browser…",
        ["SignedInAs"] = "Signed in as {0}.",
        ["SignInCancelled"] = "Sign-in cancelled.",
        ["CloudNotSignedIn"] = "Not signed in.",
        ["CloudNoPassphrase"] = "Set the encryption passphrase in Settings to sync.",
        ["CloudSyncing"] = "Syncing…",
        ["CloudWrongPassphrase"] = "The cloud file was encrypted with a different passphrase.",
        ["CloudDownloaded"] = "Downloaded from the cloud: {0} connections.",
        ["CloudUploaded"] = "Uploaded to {0}.",
        ["CloudUpToDate"] = "Up to date with the cloud.",
        ["CloudFailed"] = "Cloud: {0}",
        ["GoogleScopeMissing"] = "Google did not grant access to Drive: sign in again and tick the Google Drive box on Google's permissions page.",
        ["MicrosoftScopeMissing"] = "Microsoft did not grant access to the OneDrive app folder: sign in again and accept the permission.",
        ["EmptyTree"] = "No connections yet. Add one with + and it will show up here.",
        ["EmptyTabs"] = "Double-click a connection, or select it and press Connect. Each session opens in its own tab.",
        ["Ready"] = "Ready",
        ["Connecting"] = "Connecting to {0}…",
        ["Connected"] = "Connected to {0}.",
        ["ConnectFailed"] = "Could not connect to {0}: {1}",
        ["SessionEnded"] = "{0}: session ended ({1})",
        ["SessionClosed"] = "{0}: session closed",
        ["DeleteConnectionConfirm"] = "Delete \"{0}\"?",
        ["DeleteFolderConfirm"] = "Delete folder \"{0}\" and the {1} connections inside?",
        ["Delete"] = "Delete",
        ["Cancel"] = "Cancel",
        ["FolderName"] = "Folder name",
        ["NewFolder"] = "New folder",
        ["RenameFolderTooltip"] = "Rename folder",
        ["PasswordPrompt"] = "Password for {0}@{1}",
        ["PasswordTitle"] = "Password",
        ["ShowPassword"] = "Show the password",
        ["HidePassword"] = "Hide the password",
        ["SavePassword"] = "Remember it on this PC (encrypted)",
        ["Unnamed"] = "(unnamed)",

        ["EditTitle"] = "Connection",
        ["Name"] = "Name",
        ["Kind"] = "Type",
        ["Folder"] = "Folder",
        ["Host"] = "Host",
        ["Port"] = "Port",
        ["UserName"] = "User",
        ["Password"] = "Password",
        ["PasswordHint"] = "Leave empty to be asked when connecting.",
        ["Domain"] = "Domain",
        ["PrivateKey"] = "Private key (file)",
        ["PrivateKeyHint"] = "OpenSSH or PEM file. If set, the password is the key passphrase.",
        ["BrowseTooltip"] = "Choose file",
        ["Notes"] = "Notes",
        ["RdpSmartSizing"] = "Fit the desktop to the tab",
        ["RdpClipboard"] = "Clipboard (text, images and files)",
        ["RdpDrives"] = "Drives of this PC (copy and move files with Explorer)",
        ["FtpsMode"] = "Encryption",
        ["FtpsNone"] = "None (plain FTP)",
        ["FtpsExplicit"] = "FTPS explicit (AUTH TLS, port 21)",
        ["FtpsImplicit"] = "FTPS implicit (port 990)",
        ["UseScp"] = "Transfer with SCP instead of SFTP (browsing always uses SFTP)",
        ["RemotePath"] = "Remote folder to open",
        ["LocalPath"] = "Local folder to open",
        ["FilesPathsHint"] = "Leave empty for the server's default folder and your user profile.",
        ["FilesThisPc"] = "This PC",
        ["FilesUp"] = "Up one level (Backspace)",
        ["FilesRefresh"] = "Refresh",
        ["FilesNewFolder"] = "New folder (F7)",
        ["FilesRename"] = "Rename (F2)",
        ["FilesDelete"] = "Delete (Del)",
        ["FilesUpload"] = "Upload the selection to the server (F5, or drag it to the other side)",
        ["FilesDownload"] = "Download the selection to this PC (F5, or drag it to the other side)",
        ["FilesName"] = "Name",
        ["FilesSize"] = "Size",
        ["FilesModified"] = "Modified",
        ["FilesCount"] = "{0} folders, {1} files",
        ["FilesItems"] = "{0} items",
        ["FilesDeleteConfirm"] = "Delete {0}? Folders go with everything inside; there is no recycle bin.",
        ["FilesUploading"] = "Uploading {0} · {1} of {2}",
        ["FilesDownloading"] = "Downloading {0} · {1} of {2}",
        ["FilesDone"] = "Transfer finished.",
        ["FilesCancelled"] = "Transfer cancelled.",
        ["FilesCancel"] = "Cancel the transfer",
        ["OpenNotFound"] = "No connection named \"{0}\".",
        ["PermsTooltip"] = "Permissions and owner (Unix servers)",
        ["PermsTitle"] = "Permissions and owner",
        ["PermsPermissions"] = "Permissions",
        ["PermsRead"] = "Read",
        ["PermsWrite"] = "Write",
        ["PermsExecute"] = "Execute",
        ["PermsOwner"] = "Owner",
        ["PermsGroup"] = "Group",
        ["PermsOthers"] = "Others",
        ["PermsOctal"] = "Octal",
        ["PermsOwnership"] = "Owner and group",
        ["PermsOwnerHint"] = "Names or numeric ids; leave empty to keep. SFTP shows ids; changing by name runs chown over SSH. Most FTP servers do not allow changing the owner.",
        ["PermsRecursive"] = "Apply to everything inside the folders",
        ["PermsApply"] = "Apply",
        ["PermsApplied"] = "Permissions applied.",
        ["TabGeneral"] = "General",
        ["TabDisplay"] = "Display",
        ["TabResources"] = "Local resources",
        ["TabExperience"] = "Experience",
        ["TabAdvanced"] = "Advanced",
        ["RdpSizeTitle"] = "Remote desktop size",
        ["RdpSizeFit"] = "Fit the tab (follows the window)",
        ["RdpSizeCustom"] = "Custom…",
        ["RdpWidth"] = "Width",
        ["RdpHeight"] = "Height",
        ["RdpSizeHint"] = "Fit the tab asks the server for the size that fits (crisp, no bars). A fixed size is scaled to the tab.",
        ["RdpSizeInvalid"] = "Width and height must be numbers of at least 200 pixels.",
        ["RdpColorDepth"] = "Colours",
        ["RdpColor15"] = "High colour (15 bit)",
        ["RdpColor16"] = "High colour (16 bit)",
        ["RdpColor24"] = "True colour (24 bit)",
        ["RdpColor32"] = "Highest quality (32 bit)",
        ["RdpMultiMonitor"] = "Use all my monitors in full screen",
        ["RdpConnectionBar"] = "Show the connection bar in full screen",
        ["RdpAudio"] = "Remote audio playback",
        ["RdpAudioLocal"] = "Play on this PC",
        ["RdpAudioRemote"] = "Play on the remote computer",
        ["RdpAudioNone"] = "Do not play",
        ["RdpAudioCapture"] = "Record from this PC (microphone)",
        ["RdpKeyboard"] = "Windows key combinations (Alt+Tab, Win…)",
        ["RdpKeyboardLocal"] = "On this PC",
        ["RdpKeyboardRemote"] = "On the remote computer",
        ["RdpKeyboardFullScreen"] = "On the remote computer only in full screen",
        ["RdpDevicesTitle"] = "Local devices and resources to use in the remote session",
        ["RdpPrinters"] = "Printers",
        ["RdpSmartCards"] = "Smart cards and Windows Hello",
        ["RdpPorts"] = "Serial ports",
        ["RdpDevices"] = "Other Plug and Play devices (cameras, players…)",
        ["RdpExperienceTitle"] = "Visual effects (turn off on slow links)",
        ["RdpWallpaper"] = "Desktop background",
        ["RdpFontSmoothing"] = "Font smoothing",
        ["RdpComposition"] = "Desktop composition",
        ["RdpWindowDrag"] = "Show window contents while dragging",
        ["RdpMenuAnimation"] = "Menu and window animation",
        ["RdpVisualStyles"] = "Visual styles",
        ["RdpBitmapCache"] = "Persistent bitmap caching",
        ["RdpReconnectTitle"] = "Connection",
        ["RdpAutoReconnect"] = "Reconnect if the connection is dropped",
        ["RdpAuthLevel"] = "If server authentication fails",
        ["RdpAuthConnect"] = "Connect and don't warn me",
        ["RdpAuthWarn"] = "Warn me",
        ["RdpAuthRefuse"] = "Do not connect",
        ["RdpAdminSession"] = "Administration session (console, /admin)",
        ["RdpGatewayTitle"] = "Remote Desktop Gateway",
        ["RdpGatewayNone"] = "Do not use a gateway",
        ["RdpGatewayAlways"] = "Always use the gateway",
        ["RdpGatewayBypassLocal"] = "Use the gateway except for local addresses",
        ["RdpGatewayHost"] = "Gateway server",
        ["RdpGatewaySame"] = "Use the same user and password as the remote desktop",
        ["Save"] = "Save",
        ["NameRequired"] = "The name and the host are required.",

        ["SshNoCredentials"] = "No password or private key to sign in with.",
        ["RdpDnsError"] = "the server name could not be resolved",
        ["RdpNoConnection"] = "the server is not answering",
        ["RdpSocketClosed"] = "the connection was closed by the server",
        ["RdpAuthFailed"] = "authentication failed",
        ["RdpDisconnected"] = "disconnected (code {0})",
    };

    private static readonly Dictionary<string, string> Spanish = new()
    {
        ["AppTitle"] = "sOC Remote Connections Manager",
        ["AboutTitle"] = "Acerca de",
        ["AboutTooltip"] = "Acerca de",
        ["AboutDescription"] = "Tus conexiones RDP y SSH en un sitio: un árbol de servidores, y cada sesión en su pestaña.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contacto",
        ["WriteAuthor"] = "Escribir al autor",
        ["ContactHint"] = "Sugerencias, fallos e ideas: se lee todo.",
        ["LanguageTitle"] = "Idioma",
        ["LanguageHint"] = "El idioma se aplica al momento.",
        ["Privacy"] = "Privacidad",
        ["PrivacyText"] = "Las conexiones se guardan solo en este PC, en tu perfil de usuario; las contraseñas van cifradas por Windows (DPAPI) para tu cuenta. Las sesiones van directas de este PC a tus servidores. Nada sale a ningún otro sitio. Sin anuncios, sin rastreadores, sin analítica.",
        ["License"] = "Licencia",
        ["LicenseText"] = "Software libre con licencia MIT. SSH.NET (MIT) y el resto de componentes de terceros están en THIRD-PARTY-NOTICES.md. El control de Escritorio remoto es el que trae Windows.",
        ["LicenseLine"] = "Licencia MIT · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Aviso legal",
        ["LegalText1"] = "Este software se proporciona «tal cual», sin garantía de ningún tipo, expresa o implícita.",
        ["LegalText2"] = "En ningún caso los autores serán responsables de reclamaciones, daños u otras responsabilidades derivadas del uso de este software.",
        ["WarningText"] = "⚠️ Úsalo bajo tu responsabilidad",
        ["Close"] = "Cerrar",
        ["LanguageTooltip"] = "Español / English",

        ["SearchHint"] = "Buscar…",
        ["NewFolderTooltip"] = "Carpeta nueva",
        ["NewConnectionTooltip"] = "Conexión nueva",
        ["EditTooltip"] = "Editar",
        ["DuplicateTooltip"] = "Duplicar",
        ["DeleteTooltip"] = "Borrar",
        ["ConnectTooltip"] = "Conectar",
        ["DisconnectTooltip"] = "Desconectar esta pestaña",
        ["FullScreenTooltip"] = "Pantalla completa (F11; Ctrl+Esc para volver)",
        ["ExitFullScreenTooltip"] = "Salir de pantalla completa (Ctrl+Esc)",
        ["OpenFileTooltip"] = "Abrir la carpeta del fichero de conexiones",
        ["ImportTooltip"] = "Importar de Remote Desktop Manager (.rdm)",
        ["Imported"] = "Importadas {0} conexiones ({1} ya existían, {2} de tipos no admitidos se han dejado fuera). Las contraseñas no se importan: se piden al conectar.",
        ["ImportFailed"] = "No se ha podido importar: {0}",
        ["SettingsTooltip"] = "Ajustes: dónde se guardan las conexiones",
        ["ImportTitle"] = "Importar de Remote Desktop Manager",
        ["ImportIntro"] = "Lee un fichero .rdm exportado y conserva sus carpetas. Las contraseñas no se importan (RDM las cifra con su clave).",
        ["SettingsTitle"] = "Ajustes",
        ["StorageTitle"] = "Dónde se guardan las conexiones",
        ["StorageIntro"] = "Solo en este PC, o en tu Google Drive o tu OneDrive para que te sigan a otros equipos. En la nube el fichero va cifrado con una frase que solo tú conoces.",
        ["StorageLocal"] = "Este PC",
        ["StorageLocalHint"] = "Las conexiones se quedan en el perfil de usuario de este PC; nada sale de él.",
        ["StorageGoogleHint"] = "Entrar con Google: el fichero va a la carpeta privada de esta aplicación en tu Drive (sin acceso al resto de tus ficheros).",
        ["StorageOneDriveHint"] = "Entrar con Microsoft: el fichero va a la carpeta de la aplicación en tu OneDrive (sin acceso al resto de tus ficheros).",
        ["StorageAccount"] = "Dentro como {0} · última sincronización: {1}",
        ["StorageNowLocal"] = "Las conexiones se quedan ahora en este PC. Lo subido sigue en tu cuenta hasta que lo borres allí.",
        ["Never"] = "nunca",
        ["PassphraseTitle"] = "Frase de cifrado",
        ["PassphraseIntro"] = "El fichero de la nube va cifrado con ella (AES-256). No sale de este PC ni se guarda en tu cuenta: usa la misma en cada equipo. Si la olvidas, la copia de la nube no se puede leer.",
        ["PassphraseSaveTooltip"] = "Guardar la frase y sincronizar",
        ["SyncNowTooltip"] = "Sincronizar ahora",
        ["PassphraseSet"] = "Frase guardada en este PC.",
        ["PassphraseMissing"] = "Aún no hay frase: no se sube nada hasta que pongas una.",
        ["PassphraseTooShort"] = "Usa al menos 8 caracteres.",
        ["SigningInBrowser"] = "Terminando la entrada en el navegador…",
        ["SignedInAs"] = "Dentro como {0}.",
        ["SignInCancelled"] = "Entrada cancelada.",
        ["CloudNotSignedIn"] = "No has entrado con ninguna cuenta.",
        ["CloudNoPassphrase"] = "Pon la frase de cifrado en Ajustes para sincronizar.",
        ["CloudSyncing"] = "Sincronizando…",
        ["CloudWrongPassphrase"] = "El fichero de la nube está cifrado con otra frase.",
        ["CloudDownloaded"] = "Bajado de la nube: {0} conexiones.",
        ["CloudUploaded"] = "Subido a {0}.",
        ["CloudUpToDate"] = "Al día con la nube.",
        ["CloudFailed"] = "Nube: {0}",
        ["GoogleScopeMissing"] = "Google no ha concedido el acceso a Drive: vuelve a entrar y marca la casilla de Google Drive en la pantalla de permisos de Google.",
        ["MicrosoftScopeMissing"] = "Microsoft no ha concedido el acceso a la carpeta de la aplicación en OneDrive: vuelve a entrar y acepta el permiso.",
        ["EmptyTree"] = "Todavía no hay conexiones. Añade una con + y aparecerá aquí.",
        ["EmptyTabs"] = "Haz doble clic en una conexión, o selecciónala y pulsa Conectar. Cada sesión se abre en su pestaña.",
        ["Ready"] = "Listo",
        ["Connecting"] = "Conectando con {0}…",
        ["Connected"] = "Conectado con {0}.",
        ["ConnectFailed"] = "No se ha podido conectar con {0}: {1}",
        ["SessionEnded"] = "{0}: sesión terminada ({1})",
        ["SessionClosed"] = "{0}: sesión cerrada",
        ["DeleteConnectionConfirm"] = "¿Borrar «{0}»?",
        ["DeleteFolderConfirm"] = "¿Borrar la carpeta «{0}» y las {1} conexiones que tiene dentro?",
        ["Delete"] = "Borrar",
        ["Cancel"] = "Cancelar",
        ["FolderName"] = "Nombre de la carpeta",
        ["NewFolder"] = "Carpeta nueva",
        ["RenameFolderTooltip"] = "Renombrar la carpeta",
        ["PasswordPrompt"] = "Contraseña de {0}@{1}",
        ["PasswordTitle"] = "Contraseña",
        ["ShowPassword"] = "Ver la contraseña",
        ["HidePassword"] = "Ocultar la contraseña",
        ["SavePassword"] = "Recordarla en este PC (cifrada)",
        ["Unnamed"] = "(sin nombre)",

        ["EditTitle"] = "Conexión",
        ["Name"] = "Nombre",
        ["Kind"] = "Tipo",
        ["Folder"] = "Carpeta",
        ["Host"] = "Servidor",
        ["Port"] = "Puerto",
        ["UserName"] = "Usuario",
        ["Password"] = "Contraseña",
        ["PasswordHint"] = "Déjala vacía para que se pida al conectar.",
        ["Domain"] = "Dominio",
        ["PrivateKey"] = "Clave privada (fichero)",
        ["PrivateKeyHint"] = "Fichero OpenSSH o PEM. Si se pone, la contraseña es la de la clave.",
        ["BrowseTooltip"] = "Elegir fichero",
        ["Notes"] = "Notas",
        ["RdpSmartSizing"] = "Ajustar el escritorio a la pestaña",
        ["RdpClipboard"] = "Portapapeles (texto, imágenes y ficheros)",
        ["RdpDrives"] = "Unidades de este PC (copiar y mover ficheros con el Explorador)",
        ["FtpsMode"] = "Cifrado",
        ["FtpsNone"] = "Ninguno (FTP en claro)",
        ["FtpsExplicit"] = "FTPS explícito (AUTH TLS, puerto 21)",
        ["FtpsImplicit"] = "FTPS implícito (puerto 990)",
        ["UseScp"] = "Transferir por SCP en vez de SFTP (la navegación va siempre por SFTP)",
        ["RemotePath"] = "Carpeta remota al abrir",
        ["LocalPath"] = "Carpeta local al abrir",
        ["FilesPathsHint"] = "Vacías: la carpeta que dé el servidor y tu perfil de usuario.",
        ["FilesThisPc"] = "Este equipo",
        ["FilesUp"] = "Subir un nivel (Retroceso)",
        ["FilesRefresh"] = "Actualizar",
        ["FilesNewFolder"] = "Nueva carpeta (F7)",
        ["FilesRename"] = "Renombrar (F2)",
        ["FilesDelete"] = "Borrar (Supr)",
        ["FilesUpload"] = "Subir la selección al servidor (F5, o arrástrala al otro lado)",
        ["FilesDownload"] = "Bajar la selección a este PC (F5, o arrástrala al otro lado)",
        ["FilesName"] = "Nombre",
        ["FilesSize"] = "Tamaño",
        ["FilesModified"] = "Modificado",
        ["FilesCount"] = "{0} carpetas, {1} ficheros",
        ["FilesItems"] = "{0} elementos",
        ["FilesDeleteConfirm"] = "¿Borrar {0}? Las carpetas se van con todo lo de dentro; no hay papelera.",
        ["FilesUploading"] = "Subiendo {0} · {1} de {2}",
        ["FilesDownloading"] = "Bajando {0} · {1} de {2}",
        ["FilesDone"] = "Transferencia terminada.",
        ["FilesCancelled"] = "Transferencia cancelada.",
        ["FilesCancel"] = "Cancelar la transferencia",
        ["OpenNotFound"] = "No hay ninguna conexión que se llame «{0}».",
        ["PermsTooltip"] = "Permisos y propietario (servidores Unix)",
        ["PermsTitle"] = "Permisos y propietario",
        ["PermsPermissions"] = "Permisos",
        ["PermsRead"] = "Leer",
        ["PermsWrite"] = "Escribir",
        ["PermsExecute"] = "Ejecutar",
        ["PermsOwner"] = "Propietario",
        ["PermsGroup"] = "Grupo",
        ["PermsOthers"] = "Otros",
        ["PermsOctal"] = "Octal",
        ["PermsOwnership"] = "Propietario y grupo",
        ["PermsOwnerHint"] = "Nombres o ids numéricos; vacío = no cambiar. SFTP enseña ids; cambiar por nombre lanza chown por SSH. La mayoría de servidores FTP no dejan cambiar el propietario.",
        ["PermsRecursive"] = "Aplicar a todo lo de dentro de las carpetas",
        ["PermsApply"] = "Aplicar",
        ["PermsApplied"] = "Permisos aplicados.",
        ["TabGeneral"] = "General",
        ["TabDisplay"] = "Pantalla",
        ["TabResources"] = "Recursos locales",
        ["TabExperience"] = "Experiencia",
        ["TabAdvanced"] = "Avanzado",
        ["RdpSizeTitle"] = "Tamaño del escritorio remoto",
        ["RdpSizeFit"] = "Ajustar a la pestaña (sigue a la ventana)",
        ["RdpSizeCustom"] = "A medida…",
        ["RdpWidth"] = "Ancho",
        ["RdpHeight"] = "Alto",
        ["RdpSizeHint"] = "«Ajustar a la pestaña» pide al servidor el tamaño que cabe (nítido, sin barras). Un tamaño fijo se escala a la pestaña.",
        ["RdpSizeInvalid"] = "Ancho y alto han de ser números de al menos 200 píxeles.",
        ["RdpColorDepth"] = "Colores",
        ["RdpColor15"] = "Color de alta densidad (15 bits)",
        ["RdpColor16"] = "Color de alta densidad (16 bits)",
        ["RdpColor24"] = "Color verdadero (24 bits)",
        ["RdpColor32"] = "Máxima calidad (32 bits)",
        ["RdpMultiMonitor"] = "Usar todos los monitores en pantalla completa",
        ["RdpConnectionBar"] = "Mostrar la barra de conexión en pantalla completa",
        ["RdpAudio"] = "Audio remoto",
        ["RdpAudioLocal"] = "Reproducir en este PC",
        ["RdpAudioRemote"] = "Reproducir en el equipo remoto",
        ["RdpAudioNone"] = "No reproducir",
        ["RdpAudioCapture"] = "Grabar desde este PC (micrófono)",
        ["RdpKeyboard"] = "Combinaciones de teclas de Windows (Alt+Tab, Win…)",
        ["RdpKeyboardLocal"] = "En este PC",
        ["RdpKeyboardRemote"] = "En el equipo remoto",
        ["RdpKeyboardFullScreen"] = "En el equipo remoto solo a pantalla completa",
        ["RdpDevicesTitle"] = "Dispositivos y recursos locales que se usan en la sesión remota",
        ["RdpPrinters"] = "Impresoras",
        ["RdpSmartCards"] = "Tarjetas inteligentes y Windows Hello",
        ["RdpPorts"] = "Puertos serie",
        ["RdpDevices"] = "Otros dispositivos Plug and Play (cámaras, reproductores…)",
        ["RdpExperienceTitle"] = "Efectos visuales (desactívalos en conexiones lentas)",
        ["RdpWallpaper"] = "Fondo de escritorio",
        ["RdpFontSmoothing"] = "Suavizado de fuentes",
        ["RdpComposition"] = "Composición del escritorio",
        ["RdpWindowDrag"] = "Mostrar el contenido de la ventana al arrastrarla",
        ["RdpMenuAnimation"] = "Animación de menús y ventanas",
        ["RdpVisualStyles"] = "Estilos visuales",
        ["RdpBitmapCache"] = "Caché persistente de mapas de bits",
        ["RdpReconnectTitle"] = "Conexión",
        ["RdpAutoReconnect"] = "Volver a conectar si se corta la conexión",
        ["RdpAuthLevel"] = "Si falla la autenticación del servidor (certificado)",
        ["RdpAuthConnect"] = "Conectar sin avisar",
        ["RdpAuthWarn"] = "Avisar",
        ["RdpAuthRefuse"] = "No conectar",
        ["RdpAdminSession"] = "Sesión de administración (consola, /admin)",
        ["RdpGatewayTitle"] = "Puerta de enlace de Escritorio remoto",
        ["RdpGatewayNone"] = "No usar puerta de enlace",
        ["RdpGatewayAlways"] = "Usar siempre la puerta de enlace",
        ["RdpGatewayBypassLocal"] = "Usar la puerta de enlace salvo para direcciones locales",
        ["RdpGatewayHost"] = "Servidor de puerta de enlace",
        ["RdpGatewaySame"] = "Usar el mismo usuario y contraseña que el escritorio remoto",
        ["Save"] = "Guardar",
        ["NameRequired"] = "El nombre y el servidor son obligatorios.",

        ["SshNoCredentials"] = "No hay contraseña ni clave privada con la que entrar.",
        ["RdpDnsError"] = "no se ha podido resolver el nombre del servidor",
        ["RdpNoConnection"] = "el servidor no responde",
        ["RdpSocketClosed"] = "el servidor ha cerrado la conexión",
        ["RdpAuthFailed"] = "la autenticación ha fallado",
        ["RdpDisconnected"] = "desconectado (código {0})",
    };

    public static string Language { get; private set; } =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "es" ? "es" : "en";

    public static event Action? LanguageChanged;

    public static void Toggle()
    {
        Language = Language == "es" ? "en" : "es";
        LanguageChanged?.Invoke();
    }

    public static string Get(string key)
    {
        var table = Language == "es" ? Spanish : English;
        return table.TryGetValue(key, out var value) ? value
            : English.TryGetValue(key, out var fallback) ? fallback
            : string.Empty;
    }

    public static string Format(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), args);
}

/// <summary><c>{loc:T Clave}</c> en el XAML.</summary>
[MarkupExtensionReturnType(typeof(string))]
public sealed class TExtension : MarkupExtension
{
    public TExtension()
    {
    }

    public TExtension(string key) => Key = key;

    [ConstructorArgument("key")]
    public string Key { get; set; } = string.Empty;

    public override object ProvideValue(IServiceProvider serviceProvider) => Loc.Get(Key);
}
